### PR TITLE
PPL-18554 Package upload to CodeArtifact

### PR DESCRIPTION
**Pull request by boreyko**
These changes add a CI config file for proper package uploading.

### CODE REVIEW

**Comment by istepura** [comment]
You might want to bump version to ,say, 5.5.8, otherwise you might get a `409` error from CodeArtifact, since `5.5.7` is already published

**Comment by boreyko** [comment]
The current version of this package is `0.5.7+ppl`, which is also on CodeArtifact, but actually, I thought about deleting it right before merging this MR.

**Comment by istepura** [comment]
@boreyko my main concern is that even if you replace the file in CodeArtifact, the signature of the package may change (I don't know for sure), so `poetry` will complain because it won't match the one from its `.lock` file. I'm not sure if `pip` does signature checking as well

**Comment by boreyko** [comment]
@istepura You're right, signatures will differ, so I'll update the `.lock` file before migrating `salesforce-integration` to CodeArtifact.

**Comment by le-r-on** [comment]
Sorry - merge by mistake :(

**Pull request merged**
